### ISSUE TITLE
Ultimaker S5 -7.1.3 Webcam

### ISSUE THREAD

**Issue by juanbu123** [SmithyAT/UltiTuner#3]
Hi,
I am on 7.1.3 on an Ultimaker S5. The adding another webcam is not working for me. Perhaps is the firmware I currently have,

This is the message print out in terminal.
"Checking printer/firmware compatibility.....done, but not compatible"

Thanks

**Comment by SmithyAT** [comment]
Hi
Is it possible that you have already enabled it?
It works on the S5 with the latest firmware, but I just checked the code and see that when you already fired to webcam command once, that you will get the error message "not compatible" when you want to send it again.

I have to rewrite the error messages to be more specific, otherwise it is misleading.

**Comment by SmithyAT** [comment]
First run:
`❯ ./ultituner -p 192.168.0.55 webcam
UltiTuner 0.9.0 - Copyright by Smithy (Christian Schmied)
Connecting to the printer 192.168.0.55.....done, connected
--------------------
Ultimaker-S5
model: 9051
version: 7.1.3
--------------------
Checking printer/firmware compatibility.....done, compatible
Changing firewall rules.....done`
 
Second run:
`❯ ./ultituner -p 192.168.0.55 webcam
UltiTuner 0.9.0 - Copyright by Smithy (Christian Schmied)
Connecting to the printer 192.168.0.55.....done, connected
--------------------
Ultimaker-S5
model: 9051
version: 7.1.3
--------------------
Checking printer/firmware compatibility.....done, but not compatible`
 
When I find more time I will rewrite the check for compatibility and try to give a more specific and useful error message.

**Comment by SmithyAT** [comment]
First run:
```
./ultituner -p 192.168.0.55 webcam
UltiTuner 0.9.0 - Copyright by Smithy (Christian Schmied)
Connecting to the printer 192.168.0.55.....done, connected

Ultimaker-S5
model: 9051
version: 7.1.3

Checking printer/firmware compatibility.....done, compatible
Changing firewall rules.....done
```
 
Second run:
```
./ultituner -p 192.168.0.55 webcam
UltiTuner 0.9.0 - Copyright by Smithy (Christian Schmied)
Connecting to the printer 192.168.0.55.....done, connected

Ultimaker-S5
model: 9051
version: 7.1.3

Checking printer/firmware compatibility.....done, but not compatible
```
 
When I find more time I will rewrite the check for compatibility and try to give a more specific and useful error message.

**Comment by SmithyAT** [comment]
Or another possibility is, that you have enabled the firewall on your printer. In that case it is also not working, because then all connections are blocked except the one to the digital factory.
