### ISSUE TITLE
Printer Authentication 

### ISSUE THREAD

**Issue by ps195415** [SmithyAT/UltiTuner#4]
this is a question and not an error message. i am trying to make the same as you but only for the clearbed command in python for a project in my intership. I'm trying to make an ssh connection but I don't know how you did that without using the printer Authentication. because I don't see in the code that you use
credential to connect.

sorry for my bad English.

**Comment by SmithyAT** [comment]
You need to enable the developer mode on your printer to enable the SSH daemon. 
Then you can SSH into your printer with username: root and password: ultimaker
And you have to handle the SSH host key in your code, because normally with the first connection you have to accept the host key if it is not already in your known_hosts file. I have set a flag to ignore and not check the host key, which is the easiest one for that case.

Hope that helps....

**Comment by ps195415** [comment]
Yes it help thank you. now I only need to look at how to send the dbus-send with python.

**Comment by SmithyAT** [comment]
I think the easiest method would be to use something like check_call in python to call dbus-send on the system itself like I do in my tool.

But check the source code of the printer, it is all python, so maybe you find something else which works nicer than just calling another executable.

**Comment by ps195415** [comment]
Hé SmithyAt, I tried to make how you said with check_call to call dbus-send on the system. 

DBUS_SEND = ["dbus-send", "--system", "--dest=nl.ultimaker.printer",
            "--type=method_call",   "--print-reply", "/nl/ultimaker/printer",
             "nl.ultimaker.messageProcedure", "string:\"REPRINT_AFTER_ABORT\" ",
             "string:\"ABORT\""]

        dbus_send_command = ''.join(n for n in DBUS_SEND)
        #Clear the printer state
        result = subprocess.run(['ssh', client, dbus_send_command], capture_output=True)
        print(result.stdout)

this is the imported part of the code. I don't know a lot about dbus, subprocess and linux, that is why I wanted to know if maybe this code is good before I tested on the printer it self.

**Comment by SmithyAT** [comment]
You just use a function (check_call or subprocess.run) to run a system utility, in that case it is the command bus-send. The process does exactly the same as when you type the command manually when you are logged in your printer. 

I haven't done much in the last 2 years with python anymore, but I think it should work. I use check_call, but subprocess.run should do nearly the same. Dn't know the difference out of my head.
